DROP DATABASE IF EXISTS subscriptionsDB;
CREATE DATABASE IF NOT EXISTS subscriptionsDB;
USE subscriptionsDB;
CREATE TABLE IF NOT EXISTS SUBSCRIBER
(
    ID   INTEGER NOT NULL AUTO_INCREMENT,
    S_NAME VARCHAR(14) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLICATION
(
    ID   INTEGER  NOT NULL AUTO_INCREMENT,
    P_NAME VARCHAR(14) NOT NULL,
    PRIMARY KEY (ID)

    );

CREATE TABLE IF NOT EXISTS SUBSCRIPTION
(
    ID          INTEGER NOT NULL AUTO_INCREMENT,
    SUBSCRIBER  INTEGER NOT NULL,
    PUBLICATION INTEGER NOT NULL,
    CONSTRAINT FK_SUBSCRIBER FOREIGN KEY (SUBSCRIBER) REFERENCES SUBSCRIBER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_PUBLICATION FOREIGN KEY (PUBLICATION) REFERENCES PUBLICATION (ID) ON DELETE CASCADE,
    PRIMARY KEY (ID)

    );

